services:
  db_sorteio_feliz:
    image: postgres
    container_name: db_sorteio_feliz
    restart: always 
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data

  node_app_sorteio_feliz:
    container_name: node_app_sorteio_feliz
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_sorteio_feliz 
    env_file:
      - back-end/.env

  app_react_sorteio_feliz:
    container_name: app_react_sorteio_feliz
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx_sorteio_feliz:
    container_name: nginx_sorteio_feliz
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_sorteio_feliz
      - node_app_sorteio_feliz
      - app_react_sorteio_feliz

volumes:
  pg:
  build_react: