services:
  db_sorteio_feliz:
    image: postgres
    container_name: db_sorteio_feliz
    restart: always 
    ports:
      - 1234:5432
    env_file:
      - back-end/.env.test

  node_app_sorteio_feliz:
    container_name: node_app_sorteio_feliz
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_sorteio_feliz 
    env_file:
      - back-end/.env.test
      
    
