services:
  db_sorteio_feliz:
    image: postgres:13
    container_name: db_sorteio_feliz
    restart: always 
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  node_app_sorteio_feliz:
    container_name: node_app_sorteio_feliz
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_sorteio_feliz 
    env_file:
      - .env
    

volumes:
  pg: